version: '3'

services:
  toolbox:
    image: Anfaal25/toolbox:latest
    ports:
      - "8080:8080"  # Example port mapping
    volumes:
      - /path/to/your/local/files:/container/mount/point  # Example volume mapping
    environment:
      - ENV_VARIABLE=value  # Example environment variable
    networks:
      - your_network_name  # Example network

networks:
  your_network_name:
    driver: bridge
