version: '3.8'
services:

  # Building and testing environment
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/growlf/toolbox:testing
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    volumes: portainerVolume:/var/run/docker.sock
    network_mode: "host"

volumes:
  portainerVolume: